; HALSER Wind Interface Firmware
; Autonnic A5120 wind instrument to NMEA 2000 gateway

[platformio]
default_envs = halser

[env:halser]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
lib_ldf_mode = deep

upload_speed = 2000000
monitor_speed = 115200

lib_deps =
    SignalK/SensESP @ ^3.2.0
    SensESP/NMEA0183 @ ^3.1.0
    adafruit/Adafruit SSD1306 @ ^2.5.1
    adafruit/Adafruit NeoPixel @ ^1.12
    fastled/FastLED @ 3.9.4
    ttlappalainen/NMEA2000-library @ ^4.17.2
    NMEA2000_twai=https://github.com/skarlsson/NMEA2000_twai
    esp_websocket_client=https://components.espressif.com/api/downloads/?object_type=component&object_id=b072eea5-4e65-4ced-94c3-d6f24207062d
    pfeerick/elapsedMillis @ ^1.0.6

build_flags =
    -D SENSESP_BUTTON_PIN=9
    -D PIN_RGB_LED=8
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -D SENSESP_SSL_SUPPORT=1
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
    -D USE_ESP_IDF_LOG

build_unflags = -Werror=reorder
board_build.partitions = min_spiffs.csv
board_build.sdkconfig_path = sdkconfig.defaults
monitor_filters = esp32_exception_decoder
